---
- hosts: all
  become: true
  tasks:
    - name: Ping server
      ping:
      
    - name: Disable firewall
      service:
        name: firewalld
        state: stopped
        
    - name: Add the user ansibletower
      user:
        name: ansibletower
        comment: Ansible Tower User
        
